name: screenscapetv
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1+2

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0
  http: ^1.2.0
  html: ^0.15.4
  tha_player: ^0.5.2
  wakelock_plus: ^1.2.9
  package_info_plus: ^8.1.1
  url_launcher: ^6.3.1
  installed_apps: ^2.1.1
  shared_preferences: ^2.5.4
  google_fonts: ^6.1.0
  #DESKTOP ONLY
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  window_manager: ^0.5.1
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
flutter_launcher_icons:
  image_path: "assets/icon.png"
  linux:
    generate: true
    image_path: "assets/icon.png"
